name: Backend CD

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'back-end/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build # CI ワークフローが成功した後に実行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Notify Render of new deployment (Placeholder)
      run: |
        echo "CI successful. Triggering Render deployment for back-end..."
        # Render のネイティブ連携を使用する場合、ここでの明示的なデプロイコマンドは不要なことが多いです。
        # 必要に応じて、Render API を呼び出すためのステップを追加できます。
        # 例: curl -X POST https://api.render.com/deploy/<YOUR_SERVICE_ID> -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
      working-directory: back-end
