name: Frontend Mobile App CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # 例: v1.0.0 のようなタグがプッシュされた場合
    paths:
      - 'front-end/mobile-app/**'

jobs:
  build-and-submit:
    runs-on: ubuntu-latest
    needs: build # CI ワークフローが成功した後に実行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # プロジェクトのNode.jsバージョンに合わせて変更

    - name: Install dependencies
      run: npm ci
      working-directory: front-end/mobile-app

    - name: Install EAS CLI
      run: npm install -g eas-cli

    - name: EAS Login
      run: eas login --token ${{ secrets.EXPO_TOKEN }}
      working-directory: front-end/mobile-app

    - name: Build Android app
      run: eas build --platform android --profile production --non-interactive
      working-directory: front-end/mobile-app

    - name: Build iOS app
      run: eas build --platform ios --profile production --non-interactive
      working-directory: front-end/mobile-app

    # 本番環境への提出は手動承認を推奨
    - name: Submit Android app to Google Play (Manual Approval)
      if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
      run: eas submit --platform android --latest --non-interactive
      working-directory: front-end/mobile-app
      env:
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

    - name: Submit iOS app to App Store (Manual Approval)
      if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
      run: eas submit --platform ios --latest --non-interactive
      working-directory: front-end/mobile-app
      env:
        APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
